# /var/lib/clair-config/config.yaml

clair:
  database:
    type: pgsql
# A PostgreSQL Connection string pointing to the Clair Postgres database.
# Documentation on the format can be found at: http://www.postgresql.org/docs/9.4/static/libpq-connect.html
    options:
      source: postgresql://postgres@192.168.100.10:5432/clairtest? sslmode=disable
      cachesize: 16384
# The port at which Clair will report its health status. For example, if Clair is running at
# https://clair.mycompany.com, the health will be reported at
# http://clair.mycompany.com:6061/health.
  api:
    healthport: 6061
    port: 6062
    timeout: 900s
# paginationkey can be any random set of characters. *Must be the same across all Clair instances*.
    paginationkey:
  updater:
# interval defines how often Clair will check for updates from its upstream vulnerability databases.
    interval: 6h
    enabledupdaters:
    - debian
    - ubuntu
    - rhel
    - oracle
    - alpine
    - suse
    notifier:
      attempts: 3
      renotifyinterval: 1h
      http:
# QUAY_ENDPOINT defines the endpoint at which Quay is running.
# For example: https://myregistry.mycompany.com
# Example: http://quay.redhat2.cccr.local
        endpoint: http://quay.redhat2.cccr.local/secscan/notify
        proxy: http://localhost:6063
jwtproxy:
  signer_proxy:
  enabled: true
  listen_addr: :6063
  ca_key_file: /certificates/mitm.key  # Generated internally, do not change.
  ca_crt_file: /certificates/mitm.crt  # Generated internally, do not change.
  signer:
    issuer: security_scanner
    expiration_time: 5m
    max_skew: 1m
    nonce_length: 32
    private_key:
      type: autogenerated
      options:
        rotate_every: 12h
        key_folder: /clair/config/
        key_server:
          type: keyregistry
          options:
# QUAY_ENDPOINT defines the endpoint at which Quay is running.
# For example: https://myregistry.mycompany.com
# Example: http://quay.redhat2.cccr.local
            registry: http://quay.redhat2.cccr.local/keys/
  verifier_proxies:
  - enabled: true
    listen_addr: :6060
# If Clair is to be served via TLS, uncomment these lines. See the "Running Clair under TLS"
# section below for more information.
# key_file: /clair/config/clair.key
# crt_file: /clair/config/clair.crt
    verifier:
# CLAIR_ENDPOINT is the endpoint at which this Clair will be accessible. Note that the port
# specified here must match the listen_addr port a few lines above this.
# Example: https://clair.redhat2.cccr.local:6060
      audience: http://clair.redhat2.cccr.local:6060
      upstream: http://localhost:6062
      key_server:
        type: keyregistry
        options:
# QUAY_ENDPOINT defines the endpoint at which Quay is running.
# Example: https://myregistry.mycompany.com
# Example: http://quay.redhat2.cccr.local
          registry: http://quay.redhat2.cccr.local/keys/
